#petrol_raw creation

create or replace TABLE INFLATION_ANALYSIS.RAW.PETROL_RAW (
	CITY VARCHAR(16777216),
	DATE DATE,
	RATE FLOAT
);

#petrol_avg creation + petrol_yr_inflation creation

CREATE OR REPLACE TABLE STAGING.PETROL_STG AS
SELECT *
FROM RAW.PETROL_RAW
WHERE CITY IN ('Bengaluru','Chennai','Delhi','Hyderabad','Mumbai');

SELECT CITY, MIN(DATE) AS MIN_DATE, MAX(DATE) AS MAX_DATE
FROM STAGING.PETROL_STG
GROUP BY CITY;


CREATE or REPLACE TABLE INFLATION_ANALYSIS.ANALYTICS.PETROL_YR_AVG (
    CITY VARCHAR,
    YEAR NUMBER,
    AVG_RATE FLOAT
);
SELECT * FROM ANALYTICS.PETROL_YR_AVG;

CREATE OR REPLACE TABLE ANALYTICS.PETROL_YR_INFLATION AS
SELECT
    CITY,
    YEAR,
    AVG_RATE,
    ROUND(
        ((AVG_RATE - LAG(AVG_RATE) OVER (PARTITION BY CITY ORDER BY YEAR)) 
        / LAG(AVG_RATE) OVER (PARTITION BY CITY ORDER BY YEAR)) * 100, 
    2) AS YOY_INFLATION
FROM ANALYTICS.PETROL_YR_AVG
ORDER BY CITY, YEAR;

SELECT * 
FROM ANALYTICS.PETROL_YR_INFLATION
ORDER BY CITY, YEAR
LIMIT 500;


SELECT CITY, COUNT(*) AS Years, MIN(YEAR) AS StartYear, MAX(YEAR) AS EndYear
FROM ANALYTICS.PETROL_YR_INFLATION
GROUP BY CITY;

SELECT CITY, YEAR, COUNT(*) AS RowCount
FROM ANALYTICS.PETROL_YR_AVG
GROUP BY CITY, YEAR
HAVING COUNT(*) > 1
ORDER BY CITY, YEAR;

SELECT * 
FROM ANALYTICS.PETROL_YR_INFLATION
ORDER BY CITY, YEAR
LIMIT 76;

SELECT CITY, YEAR, YOY_INFLATION
FROM ANALYTICS.PETROL_YR_INFLATION
WHERE YEAR = (
    SELECT MIN(YEAR) 
    FROM ANALYTICS.PETROL_YR_INFLATION t2 
    WHERE t2.CITY = PETROL_YR_INFLATION.CITY
);

SELECT CITY, YEAR, YOY_INFLATION
FROM ANALYTICS.PETROL_YR_INFLATION t1
WHERE YEAR = (
    SELECT MIN(YEAR) 
    FROM ANALYTICS.PETROL_YR_INFLATION t2 
    WHERE t2.CITY = t1.CITY
)
ORDER BY CITY;

SELECT CITY, YEAR, COUNT(*) AS RowCount
FROM ANALYTICS.PETROL_YR_INFLATION
GROUP BY CITY, YEAR
HAVING COUNT(*) > 1
ORDER BY CITY, YEAR;



SELECT CITY, YEAR, COUNT(*) AS RowCount
FROM ANALYTICS.PETROL_YR_INFLATION
GROUP BY CITY, YEAR
HAVING COUNT(*) > 1
ORDER BY CITY, YEAR;

SELECT CITY, YEAR, COUNT(*) AS RowCount
FROM ANALYTICS.PETROL_YR_INFLATION t1
WHERE YOY_INFLATION = 0
  AND YEAR = (
      SELECT MIN(YEAR)
      FROM ANALYTICS.PETROL_YR_INFLATION t2
      WHERE t2.CITY = t1.CITY
  )
GROUP BY CITY, YEAR
HAVING COUNT(*) > 1
ORDER BY CITY, YEAR;

